# Generated by Django 5.1.1 on 2024-09-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_portfolioitem_delete_portfolioitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
