# Generated by Django 5.1.1 on 2024-09-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_portfolioitem_created_at_alter_portfolioitem_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=150)),
                ('instagram_url', models.CharField(max_length=200)),
                ('facebook_url', models.CharField(max_length=200)),
                ('twitter_url', models.CharField(max_length=200)),
            ],
        ),
    ]
