# Generated by Django 5.1.1 on 2024-09-19 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_portfolio_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('Portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.portfolio')),
            ],
        ),
    ]
