# Generated by Django 5.1.1 on 2024-09-20 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_remove_portfolio_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='mobil',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='service',
        ),
    ]
