# Generated by Django 5.1.1 on 2024-09-20 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='detail_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog/'),
            preserve_default=False,
        ),
    ]
