# Generated by Django 5.1.1 on 2024-09-21 07:45

import django.utils.timezone
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_blog_detail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
